DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS course;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE course (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  course_identifier TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
