q_marks = (
    'es zu verstehen, wie der experimentelle Aufbau funktioniert?',
    'das Nachdenken über systematische Fehlerquellen?',
    'Ergebnisse mit korrekter Gliederung und Formatierung zu vermitteln?',
    'die Berechnung von Messunsicherheiten zum besseren Verständnis meiner Ergebnisse?',
    'das Lesen von Artikeln in wissenschaftlichen Fachzeitschriften?',
    'das Verständnis der relevanten Gleichungen?',
    'das Erlernen der Nutzung von neuen Laborinstrumenten?',
    'das Verstehen der Leistungsgrenzen der Meßinstrumente?',
    'die Nutzung eines Computers zur graphischen Darstellung und Analyse der Daten?',
    'es zu verstehen wie die Messinstrumente und Sensoren funktionieren?',
    'meine eigenen Fragen zur Erforschung zu überlegen?',
    'der Entwurf und Aufbau von Gegenständen?',
    'die Bestätigung bereits bekannter Resultate?',
    'die Überwindung von Schwierigkeiten ohne die Hilfe des Betreuers?',
    'die Vermittlung wissenschaftlicher Ergebnisse an Kommilitonen?',
    'die Arbeit in der Gruppe?',
    'das Verständnis der Gleichungen und der physikalischen Konzepte die das untersuchte System beschreiben?',
    'basierend auf Daten und wissenschaftlicher Denkweise, Rückschlüsse zu ziehen?',
    'es, Vorhersage zu treffen um zu sehen ob meine Ergebnisse sinnvoll sind?',
    'zufällig Sachen am Experiment zu ändern bis ein Problem am Experiment verschwindet?',
    'das Verständnis der Näherungen und Vereinfachungen die in die theoretischen Vorhersagen eingehen?',
    'das Nachdenken über den Zweck der Anleitungen in der Versuchsanleitung?',
    'die Auswahl einer angemessenen Methode zur Datenanalyse (ohne explizite Anleitung)?'
)

questions = (
    'Bei der Durchführung eines Experimentes versuche ich zu verstehen wie der Versuchsaufbau funktioniert.',
    'Ich denke ich könnte gut in der Durchführung von Forschung sein, falls ich wollte.',
    'Während der Durchführung eines physikalischen Experiments denke ich nicht viel über Quellen systematischer Fehler nach.',
    'Wenn ich über die Ergebnisse eines Experiments berichte, ist mein Hauptziel einen Bericht mit korrekten Abschnitten und Formatierung zu erstellen.',
    'Das Berechnen von Messunsicherheiten hilft mir üblicherweise meine Ergebnisse besser zu verstehen.',
    'Artikel aus wissenschaftlichen Fachzeitschriften helfen mir meine eigenen Fragen zu beantworten und beim Entwurf von Experimenten.',
    'Ich führe physikalische Experimente ungern durch.',
    'Während ich ein Experiment durchführe, versuche ich die relevanten Gleichungen zu verstehen.',
    'Wenn ich auf ein neues Laborgerät stoße, bin ich mir sicher, dass ich lernen kann, für meine Zwecke gut genug damit umzugehen.',
    'Immer wenn ich ein neues Messgerät nutze, versuche ich die Grenzen seiner Leistungsfähigkeit zu verstehen.',
    'Computer sind hilfreich zur graphischen Darstellung und Analyse von Daten.',
    'Ich muss nicht verstehen, wie Sensoren und Messinstrumente funktionieren, um ein Experiment durchzuführen.',
    'Wenn ich mich genug anstrenge, kann ich erfolgreich physikalische Experimente durchführen.',
    'Wenn ich ein Experiment durchführe überlege ich mir normalerweise meine eigenen Fragen zu erforschen.',
    'Das Entwerfen und Aufbauen von Gegenständen ist ein wichtiger Teil von physikalischen Experimenten.',
    'Der Hauptzweck eines physikalischen Experimentes besteht in der Bestätigung bereits bekannter Resultate.',
    'Wenn ich auf Schwierigkeiten im Labor stoße ist mein erster Schritt, einen Experten, wie z.B. den Betreuer, zu fragen.',
    'Die Vermittlung von wissenschaftlichen Resultaten an Kommilitonen ist ein wertvoller Teil des physikalischen Experimentierens.',
    'Gruppenarbeit ist ein wichtiger Teil der Durchführung physikalischer Experimente.',
    'Ich baue gerne Sachen und arbeite gerne mit meinen Händen.',
    'Meistens kann ich ein Experiment abschließen, ohne dass ich die Gleichungen und die physikalischen Konzepte verstehe, die das untersuchte System beschreiben.',
    'Für mich ist bei der Präsentation meiner experimentellen Ergebnisse am wichtigsten, dass die Schlussfolgerungen aus meinen Daten unter Nutzung wissenschaftlicher Überlegungen hervorkommen.',
    'Wenn ich ein Experiment durchführe, versuche ich Vorhersagen zu treffen, um zu sehen ob meine Resultate sinnvoll sind.',
    'Fast alle Studierenden sind fähig ein physikalisches Experiment durchzuführen wenn sie sich Mühe geben.',
    'Um ein Problem am Experiment zu beheben ändert man üblicherweise zufällig Sachen bis das Problem verschwindet.',
    'Es ist hilfreich die vorausgesetzten Annahmen zu verstehen, die in Vorhersagen einfließen.',
    'Während ich ein Experiment durchführe folge ich einfach der Anweisung ohne über ihren Zweck nachzudenken.',
    'Ich erwarte nicht, dass die Durchführung eines Experiments mir beim Verstehen von Physik hilft.',
    'Ohne klare Anweisungen zur Datenanalyse bin ich mir unsicher über die angemessene Analysemethode.',
    'Physikalische Experimente tragen zum Wachstum des wissenschaftlichen Wissensschatzes bei.'
)
